In [2]:
import numpy as np

In [3]:
a = np.random.normal(size=(2,2))
print(a)
## matrix rank
print(np.linalg.matrix_rank(a))
print(np.linalg.det(a))
np.linalg.det(a)

[[-1.17067516 -0.07019043]
 [ 1.49950313 -0.46168986]]
2
0.6457396288363321


0.6457396288363321

## Inverse matrix

In [4]:
a1 = np.linalg.inv(a)
print(a1)
print("\n", a1 @ a)
print("\n", a @ a1)
print("\n", a @ a1 - np.eye(2))

[[-0.71497836  0.10869773]
 [-2.32214822 -1.81292135]]

 [[ 1.00000000e+00 -3.26352547e-18]
 [ 3.42672357e-16  1.00000000e+00]]

 [[ 1.00000000e+00 -9.58181807e-18]
 [ 2.16383362e-17  1.00000000e+00]]

 [[ 0.00000000e+00 -9.58181807e-18]
 [ 2.16383362e-17  0.00000000e+00]]


## (Near) singular matrices

In [5]:
## singular matrix
a = np.matrix(np.arange(1,10).reshape(3,3))
print(a)
print("rank=", np.linalg.matrix_rank(a))
np.linalg.inv(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
rank= 2


LinAlgError: Singular matrix

In [6]:
b = a + 1e-9*np.eye(3)
print(b)
print("rank=", np.linalg.matrix_rank(b))
b1 = np.linalg.inv(b)
print("\n", b1@b)
print('\n', b1@b - np.eye(3))

print("condition number\n", np.linalg.cond(b))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
rank= 3

 [[ 9.99999762e-01 -2.38418579e-07 -3.17502550e-07]
 [ 3.57627869e-07  1.00000048e+00  2.78043898e-07]
 [-2.98023224e-08  0.00000000e+00  9.99999950e-01]]

 [[-2.38418579e-07 -2.38418579e-07 -3.17502550e-07]
 [ 3.57627869e-07  4.76837158e-07  2.78043898e-07]
 [-2.98023224e-08  0.00000000e+00 -4.97816485e-08]]
condition number
 16848096215.68953


## Eigenvalues

In [7]:
a = np.matrix(np.arange(1,10).reshape(3,3))
print(a)
ev = np.linalg.eig(a)
print('\neigenvalues\n', ev)
val, vec = np.linalg.eig(a)
print('\neigenvalues\n', val)
print('\ncondition number', np.linalg.cond(a))
print('\neigenvectors\n', vec)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

eigenvalues
 (array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), matrix([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

eigenvalues
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

condition number 3.813147060626918e+16

eigenvectors
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## diagonalization

In [8]:
a = np.matrix(np.arange(1,10).reshape(3,3))
a = 0.5*(a + a.T)
print(a)
val, vec = np.linalg.eig(a)
print('\neigenvalues\n', val)
print('\neigenvectors\n', vec)
L = np.diag(val)
C = vec
print('C\n', C)
C1 = np.linalg.inv(C)
print('\nC inverse\n', C1)
print('\ndiagonal form\n', C @ L @ C1)

[[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]

eigenvalues
 [ 1.64582364e+01 -1.45823643e+00  1.62591776e-16]

eigenvectors
 [[-0.35162514 -0.84243284  0.40824829]
 [-0.55335618 -0.1647127  -0.81649658]
 [-0.75508721  0.51300744  0.40824829]]
C
 [[-0.35162514 -0.84243284  0.40824829]
 [-0.55335618 -0.1647127  -0.81649658]
 [-0.75508721  0.51300744  0.40824829]]

C inverse
 [[-0.35162514 -0.55335618 -0.75508721]
 [-0.84243284 -0.1647127   0.51300744]
 [ 0.40824829 -0.81649658  0.40824829]]

diagonal form
 [[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]
